# Домашнее задание "Линейная алгебра. Матрицы"

In [ ]:
import numpy as np

## Уровень 0:

### Задание 1
- Создайте матрицу 3 на 3, заполненную числами от 1 до 9


In [ ]:
A1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- Прибавьте к ней матрицу с единицами на диагонале


In [ ]:
# единичная матрица
A2 = np.eye(3)
A2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
A3 = A1 + A2
A3

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

- Умножьте полученную матрицу на вектор (1, 2, 3)


In [ ]:
v = np.array([1,2,3])
v

array([1, 2, 3])

In [ ]:
A4 = A3 @ v
A4

array([15., 34., 53.])

- Вычислить транспонированную матрицу от полученной в результате прибавления матрицы


In [ ]:
A5 = np.transpose(A4)
A5

array([15., 34., 53.])

- Посчитайте обратную матрицу к полученной в результате прибавления матрице

In [ ]:
A6 = np.linalg.inv(A3)
A6

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01, -2.33146835e-16],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

In [ ]:
# проверка (пройдена)
A3 @ A6

array([[ 1.00000000e+00, -3.33066907e-16,  6.66133815e-16],
       [-5.32907052e-15,  1.00000000e+00,  1.33226763e-15],
       [-1.77635684e-15, -1.11022302e-15,  1.00000000e+00]])

## Уровень 1:

### Задание 2
Найдите собственные значения и собственные вектора матрицы:

In [ ]:
m = np.array([[2, 2],
              [1, 3]])
m

array([[2, 2],
       [1, 3]])

In [ ]:
np.linalg.eig(m)

(array([1., 4.]), array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))

### Задание 3
Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

1. Сочетание: 4 * 11 - 43 * 1 = 1
    

In [ ]:
m1 = np.array([[4,1], [43,11]])
m1

array([[ 4,  1],
       [43, 11]])

In [ ]:
round(np.linalg.det(m1))

1

2. Увеличим размерность, добавив сочетание 21 * 1 - 4 * 5 = 1

In [ ]:
m2 = np.array([[11, 43, 0], [1, 4, 0], [5, 21, 1]])
m2

array([[11, 43,  0],
       [ 1,  4,  0],
       [ 5, 21,  1]])

In [ ]:
round(np.linalg.det(m2))

1

# Done!